apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "relational-mock.fullname" . } }
  labels: { { - include "relational-mock.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      { { - include "relational-mock.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "relational-mock.selectorLabels" . | nindent 8 } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: { { .Values.service.port } }
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources: { { - toYaml .Values.resources | nindent 12 } }
