apiVersion: v1
kind: Service
metadata:
  name: { { include "neo4j-mock.fullname" . } }
  labels: { { - include "neo4j-mock.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "neo4j-mock.selectorLabels" . | nindent 4 } }
